server.port=14999
#??IP
local.host=192.168.3.52
#??????????????????
DownloadDir=/mnt/baidu/twin2.0/Linux/TwinBaseGH55/Content/DownloadTemp
#UE??
local.path=/mnt/baidu/twin2.0/Linux/TwinBaseGH55/Binaries/Linux/

ueparam=-PixelStreamingEncoderMinQP=30
ueparam2=-PixelStreamingEncoderMaxQP=30