server.port=14999
#??IP
local.host=192.168.3.52
#??????????????????
DownloadDir=/mnt/baidu/twin2.0/Linux/TwinBaseGH55/Content/DownloadTemp
#UE??
local.path=/mnt/baidu/twin2.0/Linux/TwinBaseGH55/Binaries/Linux/
# Docker configuration
docker.container-name=mycoturn
docker.image-name=docker.1ms.run/coturn/coturn
docker.ue-volume-base=/mnt/baidu/app/
docker.config-mount=/mnt/baidu/app/turnserver.conf:/etc/coturn/turnserver.conf
docker.ue-image-name=signalling:ue
